server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  redis:
    url: redis://localhost:6379
    timeout: 2000ms
  cache:
    type: redis

resilience4j:
  bulkhead:
    instances:
      redirectService:
        maxConcurrentCalls: 200
        maxWaitDuration: 0